#!/usr/bin/env bash

usage() {
  man mandown
  exit 1
}

[[ "$1" == "--help" ]] && usage

if [ -t 0 ]; then
  [ $# -eq 0 ] && usage
  tmp="$(mktemp).man"
  ext="${1##*.}"
  if [ "$ext" == "md" ]; then
    from="markdown"
  else
    from="$ext"
  fi
  pandoc -s -f "$from" -t man "$1" -o "$tmp"
  man "$tmp"
  rm -f "$tmp"
else
  [ $# -eq 0 ] && usage
  from="${1:-markdown}"
  tmp="$(mktemp).$from"
  pandoc -s -f "$from" -t man "${2:--}" > "$tmp"
  man "$tmp"
  rm -f "$tmp"
fi
